version: "3"
services:
  
  ui:
   build:
      context: ./ui
      dockerfile: Dockerfile
   ports:
    -  3000:3000
   container_name: userapp-ui
   networks:
    -  userapp-stack-net
   volumes:
    -  ./ui/src:/usr/app/src
    -  ./ui/public:/usr/app/public
   depends_on:
    - api
   stdin_open: true
   tty: true

  api:
   build:
      context: ./api
      dockerfile: Dockerfile
   ports:
     - 3080:3080
   container_name: userapp-api
   networks:
     - userapp-stack-net
   volumes:
    - ./api/src:/usr/app/src
   depends_on:
    - db

  db:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongo-db
    networks:
      - userapp-stack-net
    volumes:
      - mongo-data:/data/db

networks:
  userapp-stack-net:
    driver: bridge

volumes:
  mongo-data:
    driver: local